### PR TITLE
BugFix: BranchingOperation should return all errors from children operations

### PR DESCRIPTION
**Pull request by RudyCo**
BranchingOperation was renamed to BranchingOperationWithBug.
A test case BranchingOperationFixture emphasizes the behavior of the two classes.

### CODE REVIEW

**Comment by regisbsb** [comment]
#26

**Comment by regisbsb** [comment]
Would we need a proper merge request with the Branching operation without the bug?

**Comment by RudyCo** [comment]
Yes but before, it would be great that Oren has a look at this PR because
it can impact performance.
Do you agree?
Thanks




2017-03-01 9:34 GMT+01:00 Regis Bittencourt <notifications@github.com>:

**Comment by ayende** [comment]
at a glance, this looks fine

**Pull request merged**
