### PR TITLE
Updated Common.Logging to version 3.0.0 (breaking change)

### PR DESCRIPTION
**Pull request by ggeurts**
Replaced Common.Logging 2.0.0 with Common.Logging 3.0.0. Unfortunately this is a breaking change, but needed to play nicely with other OSS projects that have already migrated to Common.Logging 3.0.0 (such as Quartz.Net).

### CODE REVIEW

**Comment by Gilligan128** [comment]
+1 for this PR to be accepted.

**Comment by gibgibber** [comment]
+1

**Comment by regisbsb** [comment]
+1

**Comment by nathanpalmer** [comment]
Thanks! Just released as 1.3

**Comment by regisbsb** [comment]
Maybe update the readme if possible please.

**Comment by nathanpalmer** [comment]
Done

**Pull request merged**
