### PR TITLE
Bug Fix for issue: JoinOperation errors are not propagated to the main EtlProcess

### PR DESCRIPTION
**Pull request by koulkov**
This pull request proposes to fix this issue: https://github.com/hibernating-rhinos/rhino-etl/issues/18
In addition, it creates a common AbstractJoinOperation shared by JoinOperation and NestedLoopsJoinOperation. So, similar code is not duplicated.
Thanks in advance for your feedback!

### CODE REVIEW

**Comment by koulkov** [comment]
Another interesting point: in "Debug" VS configuration, no error is reported !

**Comment by koulkov** [comment]
Thanks for the merge. When do you plan to release a new version of rhino-etl on NuGet?

**Comment by nathanpalmer** [comment]
@koulkov It was just released as version 1.2.6 (1.3.0 is also out which includes the Common.Logging upgrade)

**Comment by koulkov** [comment]
Thanks a lot @nathanpalmer!

**Pull request merged**
